In [2]:
import pandas as pd
import numpy as np

In [4]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [5]:
type(a1)

numpy.ndarray

In [8]:
a2= np.array([[1,2.0,3.2], [4.2,5.3,6]])
a2

array([[1. , 2. , 3.2],
       [4.2, 5.3, 6. ]])

In [14]:
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [15]:
a2

array([[1. , 2. , 3.2],
       [4.2, 5.3, 6. ]])

In [16]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [17]:
a1.shape

(3,)

In [18]:
a2.shape

(2, 3)

In [19]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [20]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [22]:
a1.dtype,a2.dtype,a3.dtype,

(dtype('int32'), dtype('float64'), dtype('int32'))

In [23]:
a1.size,a2.size,a3.size

(3, 6, 18)

In [24]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [26]:
# Create a DataFrame from a Numpy array

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.2
1  4.2  5.3  6.0

In [32]:
df1 = pd.DataFrame(a1)
df1

0
0  1
1  2
2  3

## Creating arrays

In [37]:
a4 = np.ones((3,5))
a4

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
type(a4)

numpy.ndarray

In [40]:
a5 = np.zeros((7,5))
a5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [43]:
a6 = np.arange(1,19)
a6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [45]:
a6 = np.arange(1,19,3)
a6

array([ 1,  4,  7, 10, 13, 16])

In [49]:
a7 = np.random.randint(1,15,7)
a7

array([ 2, 12,  6,  6,  2, 13,  1])

In [52]:
a77 = np.random.randint(1,15, size  = (4,4))
a77

array([[ 3,  8,  4, 13],
       [12,  1, 14, 13],
       [13,  7, 12,  4],
       [ 9, 11,  9, 14]])

In [53]:
a77.size

16

In [54]:
a77.shape

(4, 4)

In [58]:
a8 = np.random.random((5,2))
a8

array([[0.68891542, 0.11691379],
       [0.75942224, 0.23034524],
       [0.80835393, 0.6464255 ],
       [0.14871145, 0.80936208],
       [0.66847637, 0.18999166]])

In [61]:
a88 = np.random.rand(4,4,4)
a88

array([[[7.59846821e-02, 9.29188409e-01, 3.02157097e-01, 5.29674289e-01],
        [6.35785807e-01, 6.00080869e-01, 7.71924241e-01, 2.54520565e-01],
        [7.22455681e-01, 3.13639737e-01, 8.80265091e-01, 6.97633218e-01],
        [5.45666205e-01, 1.12541033e-01, 9.37918686e-01, 9.12299309e-01]],

       [[5.57248758e-01, 6.38021219e-01, 6.46185643e-04, 3.54941112e-01],
        [2.03081595e-01, 1.63881792e-01, 6.76221199e-01, 9.65951228e-01],
        [1.86133224e-01, 4.24330208e-01, 5.67652786e-01, 7.85674378e-01],
        [9.34913143e-01, 4.50515152e-01, 9.08558346e-01, 5.93095309e-01]],

       [[9.69199772e-01, 5.98869006e-01, 5.59350886e-01, 4.57809002e-01],
        [1.33134410e-02, 3.18197310e-01, 2.35044146e-01, 3.85422451e-01],
        [9.82100756e-01, 6.77854520e-02, 7.84508597e-01, 1.36924143e-02],
        [9.64566216e-01, 7.74339169e-01, 5.81765933e-01, 2.43209740e-02]],

       [[6.90567862e-01, 1.31781136e-01, 8.05285086e-01, 8.62883118e-01],
        [1.38576652e-02, 8.58073

In [74]:
a9 = np.random.randint(1,29,size = (4,2))
a9

array([[22,  9],
       [20,  6],
       [11, 13],
       [18, 16]])

In [72]:
a9.shape

(4, 2)

In [76]:
np.random.seed(seed = 0)
a9 = np.random.randint(1,29,size = (4,2))
a9

array([[13, 16],
       [22,  1],
       [ 4, 28],
       [ 4,  8]])

In [77]:
np.random.seed(seed = 0)
a9 = np.random.randint(1,29,size = (4,2))
a9

array([[13, 16],
       [22,  1],
       [ 4, 28],
       [ 4,  8]])

In [78]:
np.random.seed(seed = 0)
a99 = np.random.random((5,3))
a99

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606]])

In [81]:
np.random.seed(seed = 7)
a99 = np.random.random((5,3))
a99

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [82]:
a77

array([[ 3,  8,  4, 13],
       [12,  1, 14, 13],
       [13,  7, 12,  4],
       [ 9, 11,  9, 14]])

In [83]:
np.unique(a77)

array([ 1,  3,  4,  7,  8,  9, 11, 12, 13, 14])

In [85]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [90]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [93]:
a10 = np.random.randint(10, size= (2,3,4,5))
a10

array([[[[9, 3, 4, 0, 3],
         [5, 6, 4, 0, 4],
         [1, 5, 2, 4, 8],
         [7, 5, 7, 5, 3]],

        [[7, 6, 2, 3, 1],
         [1, 8, 4, 2, 1],
         [7, 0, 8, 8, 1],
         [2, 3, 0, 1, 1]],

        [[5, 5, 6, 0, 9],
         [3, 2, 4, 2, 8],
         [4, 9, 0, 0, 2],
         [6, 3, 9, 5, 4]]],


       [[[6, 9, 9, 9, 4],
         [8, 2, 4, 6, 5],
         [3, 5, 2, 6, 4],
         [3, 2, 5, 9, 7]],

        [[5, 8, 5, 2, 0],
         [9, 3, 2, 2, 4],
         [3, 4, 8, 7, 0],
         [2, 7, 8, 8, 4]],

        [[0, 4, 1, 7, 4],
         [9, 0, 1, 0, 6],
         [2, 0, 2, 4, 4],
         [1, 0, 0, 2, 3]]]])

In [96]:
a10[1,2:,0]

array([[0, 4, 1, 7, 4]])

In [103]:
a10[:,:,:,:4]

array([[[[9, 3, 4, 0],
         [5, 6, 4, 0],
         [1, 5, 2, 4],
         [7, 5, 7, 5]],

        [[7, 6, 2, 3],
         [1, 8, 4, 2],
         [7, 0, 8, 8],
         [2, 3, 0, 1]],

        [[5, 5, 6, 0],
         [3, 2, 4, 2],
         [4, 9, 0, 0],
         [6, 3, 9, 5]]],


       [[[6, 9, 9, 9],
         [8, 2, 4, 6],
         [3, 5, 2, 6],
         [3, 2, 5, 9]],

        [[5, 8, 5, 2],
         [9, 3, 2, 2],
         [3, 4, 8, 7],
         [2, 7, 8, 8]],

        [[0, 4, 1, 7],
         [9, 0, 1, 0],
         [2, 0, 2, 4],
         [1, 0, 0, 2]]]])

### Manipulating and comparing arrays

In [105]:
a1

array([1, 2, 3])

In [106]:
a1 + 5

array([6, 7, 8])

In [107]:
a1 * 2

array([2, 4, 6])

In [108]:
a2

array([[1. , 2. , 3.2],
       [4.2, 5.3, 6. ]])

In [109]:
a1/a2

array([[1.        , 1.        , 0.9375    ],
       [0.23809524, 0.37735849, 0.5       ]])

In [110]:
a2/a1

array([[1.        , 1.        , 1.06666667],
       [4.2       , 2.65      , 2.        ]])

In [111]:
a1 *a2

array([[ 1. ,  4. ,  9.6],
       [ 4.2, 10.6, 18. ]])

In [112]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [113]:
a2.shape

(2, 3)

In [114]:
a3.shape

(2, 3, 3)

In [117]:
a1//a2

array([[1., 1., 0.],
       [0., 0., 0.]])

In [118]:
a1**3

array([ 1,  8, 27], dtype=int32)

In [120]:
a2

array([[1. , 2. , 3.2],
       [4.2, 5.3, 6. ]])

In [119]:
a2**3

array([[  1.   ,   8.   ,  32.768],
       [ 74.088, 148.877, 216.   ]])

In [121]:
a1

array([1, 2, 3])

In [122]:
a2

array([[1. , 2. , 3.2],
       [4.2, 5.3, 6. ]])

In [123]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [124]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [125]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])